@push('head')
@php
    $base = \App\Support\Portfolio::canonical();
    $schema = ['@context' => 'https://schema.org', '@graph' => [
        ['@type' => 'Person', '@id' => $base.'/#person', 'name' => config('portfolio.name'), 'jobTitle' => config('portfolio.role'), 'url' => $base, 'email' => config('portfolio.email'), 'telephone' => '+'.config('portfolio.whatsapp'), 'sameAs' => array_values(config('portfolio.socials'))],
        ['@type' => 'WebSite', '@id' => $base.'/#website', 'name' => config('portfolio.brand').' — Fullstack Developer', 'url' => $base, 'inLanguage' => 'en', 'author' => ['@id' => $base.'/#person']],
    ]];
@endphp
<script type="application/ld+json">{!! json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
@endpush
<x-layout>
    <x-hero />
    @if($clients->isNotEmpty())
    <section class="client-strip shell" aria-labelledby="clients-title"><div class="client-heading"><h2 id="clients-title">Trusted to build digital solutions</h2><p>Turning business challenges into useful digital products.</p></div><div class="client-logos">@foreach($clients as $client)<div class="client-logo"><span>{{ $client['mark'] }}</span>{{ $client['name'] }}</div>@endforeach</div></section>
    @endif

    <section class="section section-tinted" id="problems"><div class="shell"><div class="split-heading"><x-section-heading eyebrow="THE STARTING POINT" title="Your business has enough to do." /><p class="section-intro">Your website and software should make things easier. Do any of these sound familiar?</p></div><div class="grid gap-8 md:grid-cols-2 lg:grid-cols-3 problem-grid">@foreach(config('portfolio.problems') as $problem)<x-problem-card :problem="$problem" />@endforeach</div><div class="section-footnote"><span class="accent">Let’s turn those roadblocks into a better way of working.</span><a class="text-link" href="#services">Here’s how I can help <x-icon name="arrow" size="18" /></a></div></div></section>

    <section id="services" class="section shell"><div class="split-heading"><x-section-heading eyebrow="WHAT I CAN DO FOR YOU" title="The right solution. Built around you." /><p class="section-intro">From a business website and manageable CMS to technical SEO and the system that runs your operations. Practical solutions with a clear purpose.</p></div><div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach(config('portfolio.services') as $service)<x-service-card :service="$service" :number="$loop->iteration" />@endforeach</div></section>

    <section id="about" class="section section-tinted"><div class="shell about-grid"><div class="about-visual" data-aos="fade-up"><x-profile-visual /></div><div class="about-copy"><x-section-heading eyebrow="A LITTLE ABOUT ME" title="More than just writing code." /><p>I'm Roni Zeki, the developer behind codewithronn. I’m a Fullstack Developer in Indonesia with over 6 years of experience building web applications and digital solutions.</p><p>I believe great software starts with understanding your business. Before writing a line of code, I take time to understand the problem, the people using the product, and what you want to achieve.</p><p>From company websites and internal business systems to custom applications and API integrations, I build solutions that are reliable, maintainable, and easy to use.</p><div class="about-highlights">@foreach(['6+ years of development experience', 'End-to-end fullstack development', 'Business-oriented solutions', 'Clean code & long-term support'] as $highlight)<span><x-icon name="check" size="18" />{{ $highlight }}</span>@endforeach</div><a class="text-link" href="{{ config('portfolio.socials.LinkedIn') }}" target="_blank" rel="noopener noreferrer" data-track="linkedin_clicked">More about me on LinkedIn <x-icon name="external" size="18" /></a></div></div></section>

    <section id="skills" class="section shell"><div class="split-heading"><x-section-heading eyebrow="SKILLS & EXPERTISE" title="Backend to frontend. Built to work together." /><p class="section-intro">The right tools for the job, chosen for reliability, performance, and long-term maintainability.</p></div><div class="skills-grid">@foreach(config('portfolio.skills') as $group => $skills)<article class="skill-group"><div><span class="card-number">0{{ $loop->iteration }}</span><h3>{{ $group }}</h3></div>@if(config("portfolio.skill_descriptions.$group"))<p class="skill-description">{{ config("portfolio.skill_descriptions.$group") }}</p>@endif<div class="tags">@foreach($skills as $skill)<span>{{ $skill }}</span>@endforeach</div></article>@endforeach</div></section>

    @if($projects->isNotEmpty())
    <section id="projects" class="section section-tinted"><div class="shell"><div class="split-heading"><x-section-heading eyebrow="SELECTED WORK" title="Real-world problems. Thoughtful solutions." /><div><p class="section-intro">Explore the thinking behind the build, from the first challenge to the proposed solution.</p></div></div>@if($projects->isNotEmpty())<div class="project-filters" role="group" aria-label="Filter projects" hidden>@foreach(['All projects', 'Business systems', 'Web applications', 'Websites'] as $filter)<button type="button" class="filter-button" data-filter="{{ $filter }}" aria-pressed="{{ $loop->first ? 'true' : 'false' }}">{{ $filter }}</button>@endforeach</div><p class="sr-only" id="filter-status" role="status"></p><div class="grid gap-x-8 gap-y-12 md:grid-cols-2">@foreach($projects as $project)<x-project-card :project="$project" :number="$loop->iteration" />@endforeach</div>@endif</div></section>
    @endif

    <section id="process" class="section shell"><x-section-heading eyebrow="FROM FIRST HELLO TO WHAT’S NEXT" title="A clear process. No guesswork." text="Good collaboration is as important as good code. Here’s how we get from your idea to a solution that works." /><div class="process-grid">@foreach(config('portfolio.process') as [$title, $text])<article class="process-step"><span>0{{ $loop->iteration }}</span><h3>{{ $title }}</h3><p>{{ $text }}</p></article>@endforeach</div></section>

    @if($testimonials->isNotEmpty())<section class="section section-tinted"><div class="shell"><x-section-heading eyebrow="CLIENT PERSPECTIVES" title="Good work starts with good collaboration." /><div class="grid gap-6 lg:grid-cols-3">@foreach($testimonials as $testimonial)<x-testimonial-card :testimonial="$testimonial" />@endforeach</div></div></section>@endif

    <section class="section shell why-grid"><x-section-heading eyebrow="WHY WORK WITH ME" title="A partner for the build. And beyond." text="Clear communication, considered decisions, and a focus on what your business actually needs." /><div class="reasons-grid">@foreach(config('portfolio.reasons') as $reason)<div><x-icon name="check" size="20" /><span>{{ $reason }}</span></div>@endforeach</div></section>

    <section class="cta-section shell"><div class="cta-panel"><div><p class="eyebrow">LET’S MAKE SOMETHING USEFUL</p><h2>Have a project<br>in mind<span>?</span></h2><p>Tell me about your idea, business problem, or existing system. Let’s build a better solution, together.</p><a class="button button-light" href="{{ \App\Support\Portfolio::whatsapp() }}" data-track="whatsapp_clicked">Discuss Your Project <x-icon name="external" size="20" /></a><small>No commitment required. Let’s start with a conversation.</small></div><span class="cta-arrow" aria-hidden="true">↗</span></div></section>

    <section id="contact" class="section shell contact-grid"><div><x-section-heading eyebrow="GET IN TOUCH" title="Let’s build something great." text="A new idea, an existing challenge, or just a question. I’d love to hear what you’re working on." /><div class="contact-methods"><a href="{{ \App\Support\Portfolio::whatsapp() }}" data-track="whatsapp_clicked"><span class="icon-tile"><x-icon name="chat" /></span><span><small>WHATSAPP / PHONE</small>{{ config('portfolio.phone') }}</span><x-icon name="external" size="20" /></a><a href="mailto:{{ config('portfolio.email') }}" data-track="email_clicked"><span class="icon-tile"><x-icon name="mail" /></span><span><small>EMAIL ME</small>{{ config('portfolio.email') }}</span><x-icon name="external" size="20" /></a></div><div class="contact-socials">@foreach(config('portfolio.socials') as $label => $url)<a class="text-link" href="{{ $url }}" target="_blank" rel="noopener noreferrer" data-track="{{ strtolower($label) }}_clicked">{{ $label }} <x-icon name="external" size="16" /></a>@endforeach</div><div class="location-note"><x-icon name="pin" size="18" /> Based in Indonesia. Open to working worldwide.</div></div>@if(config('portfolio.contact_form_enabled'))<x-contact-form />@else<div class="contact-form-card direct-contact"><span class="icon-tile"><x-icon name="chat" /></span><h3>Let’s start with a conversation.</h3><p>Share your idea, the challenge you’re facing, and your timeline. Reach me directly on WhatsApp or email.</p><a class="button" href="{{ \App\Support\Portfolio::whatsapp() }}" data-track="whatsapp_clicked">Discuss Your Project <x-icon name="external" /></a><a class="text-link" href="mailto:{{ config('portfolio.email') }}" data-track="email_clicked">Send an email <x-icon name="mail" size="18" /></a></div>@endif</section>
</x-layout>
