@push('head')
@php($breadcrumbs = ['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => [
    ['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => \App\Support\Portfolio::canonical()],
    ['@type' => 'ListItem', 'position' => 2, 'name' => $project['title'], 'item' => \App\Support\Portfolio::canonical('projects/'.$project['slug'])],
]])
<script type="application/ld+json">{!! json_encode($breadcrumbs, JSON_UNESCAPED_SLASHES | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
@endpush
<x-layout :title="$project['title'].' | codewithronn'" :description="$project['description']" :path="'projects/'.$project['slug']" :image="$project['image'] ?: 'images/og.webp'" :noindex="$project['placeholder'] ?? false">
    <article class="shell case-study section"><nav aria-label="Breadcrumb" class="breadcrumbs"><a href="{{ route('home') }}">Home</a><span>/</span><a href="{{ route('home') }}#projects">Projects</a><span>/</span><span aria-current="page">{{ $project['title'] }}</span></nav><p class="eyebrow">{{ $project['category'] }} · {{ $project['client'] }}</p><h1>{{ $project['title'] }}</h1>@if($project['placeholder'] ?? false)<p class="form-notice">Project details are being updated. This page is an editable project layout.</p>@endif<p class="case-intro">{{ $project['description'] }}</p><div class="tags">@foreach($project['tech'] as $tech)<span>{{ $tech }}</span>@endforeach</div><div class="case-cover"><x-project-visual :project="$project" :eager="true" /></div><div class="case-content"><div><section><p class="eyebrow">01 / THE CHALLENGE</p><h2>The business problem</h2><p>{{ $project['problem'] }}</p></section><section><p class="eyebrow">02 / THE APPROACH</p><h2>A solution that fits the workflow</h2><p>{{ $project['solution'] }}</p></section><section><p class="eyebrow">03 / THE INTENDED VALUE</p><h2>Less friction. More clarity.</h2><p>{{ $project['outcome'] }}</p></section></div><aside><h2>Core capabilities</h2><ul>@foreach($project['features'] as $feature)<li><x-icon name="check" size="18" />{{ $feature }}</li>@endforeach</ul><hr><h3>Have a similar challenge?</h3><p>Let’s talk about a solution for your business.</p><a class="button" href="{{ \App\Support\Portfolio::whatsapp('Hi Roni, saya tertarik dengan '.$project['title'].' dan ingin berdiskusi mengenai project.') }}" data-track="whatsapp_clicked">Discuss Your Project <x-icon name="external" size="17" /></a></aside></div><a class="text-link" href="{{ route('home') }}#projects">← Back to all projects</a></article>
</x-layout>
