<?php

// Public identity and services supplied by the owner. Publish only approved, real work.
return [
    'email' => env('CONTACT_TO_ADDRESS', 'ronizeki83@gmail.com'),
    'available' => env('PORTFOLIO_AVAILABLE', true),
    'indexable' => env('PORTFOLIO_INDEXABLE', false),
    'name' => 'Roni Zeki',
    'brand' => 'codewithronn',
    'role' => 'Fullstack Developer',
    'experience' => '6+',
    'phone' => '085272339039',
    'whatsapp' => '6285272339039',
    'whatsapp_message' => 'Hi Roni, saya melihat portfolio Anda dan ingin berdiskusi mengenai project.',
    'profile' => null,
    'socials' => [
        'Instagram' => 'https://www.instagram.com/codewithronn/',
        'LinkedIn' => 'https://www.linkedin.com/in/roni-zeki-02a452129/',
        'Github' => 'https://github.com/ronizeki',
    ],
    'project_types' => [
        'Company Profile',
        'Landing Page',
        'Web Application',
        'Internal Business System',
        'API / Integration',
        'Maintenance',
        'Other',
    ],
    'budgets' => [
        'Let’s discuss',
        'Under Rp 10 million',
        'Rp 10–25 million',
        'Rp 25–50 million',
        'Rp 50–100 million',
        'Rp 100 million+',
    ],
    'problems' => [
        [
            'icon' => 'window',
            'title' => 'Your website feels outdated',
            'text' => 'A first impression that no longer reflects the quality of your business.',
        ],
        [
            'icon' => 'bolt',
            'title' => 'Slow pages, lost opportunities',
            'text' => 'Visitors leave before they get to see what you have to offer.',
        ],
        [
            'icon' => 'layers',
            'title' => 'Too much manual work',
            'text' => 'Scattered spreadsheets and repetitive tasks are taking up your team’s time.',
        ],
        [
            'icon' => 'code',
            'title' => 'A system that holds you back',
            'text' => 'Small changes take too long and your application is difficult to maintain.',
        ],
        [
            'icon' => 'grid',
            'title' => 'One-size-fits-all doesn’t fit',
            'text' => 'Your workflow needs a custom application, not another workaround.',
        ],
        [
            'icon' => 'search',
            'title' => 'Hard to find online',
            'text' => 'Your customers are searching, but your website isn’t easy to discover.',
        ],
    ],
    'services' => [
        [
            'icon' => 'window',
            'title' => 'Website development',
            'text' => 'A clear, fast online presence that turns first impressions into conversations.',
            'detail' => 'Company profiles · Landing pages · Corporate websites',
        ],
        [
            'icon' => 'code',
            'title' => 'Custom web applications',
            'text' => 'Software shaped around how your business actually works, with room to grow.',
            'detail' => 'Customer portals · Booking platforms · Custom workflows',
        ],
        [
            'icon' => 'grid',
            'title' => 'Business systems',
            'text' => 'Bring your data, people, and daily operations together in one useful place.',
            'detail' => 'CRM · Inventory · Dashboards · Automation',
        ],
        [
            'icon' => 'link',
            'title' => 'APIs & integrations',
            'text' => 'Connect your tools so information flows without the extra manual work.',
            'detail' => 'REST APIs · Payments · Third-party services',
        ],
        [
            'icon' => 'bolt',
            'title' => 'Website optimization',
            'text' => 'Make your existing website faster, easier to use, and easier to discover.',
            'detail' => 'Performance · Technical SEO · Responsive improvements',
        ],
        [
            'icon' => 'shield',
            'title' => 'Maintenance & support',
            'text' => 'Keep your application reliable as your needs change after launch.',
            'detail' => 'Bug fixes · New features · Ongoing improvement',
        ],
    ],
    'skills' => [
        'Backend Development' => [
            'PHP',
            'Laravel',
            'REST API',
            'NodeJS',
            'NestJS',
            '.NET Core',
            'Golang',
            'Python'
        ],
        'Frontend Development' => [
            'HTML5',
            'CSS3',
            'JavaScript',
            'Tailwind CSS',
            'Alpine.js',
            'NextJS',
            'ReactJS',
            'VueJS',
            'InertiaJS',
        ],
        'mobile' => [
            'Flutter',
            'React Native',
        ],
        'database' => [
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'Supabase',
        ],
        'Cloud' => [
            'AWS',
            'Vercel',
            'Netlify',
        ],
        'Project Management' => [
            'Trello',
            'Jira',
            'Notion',
        ],
        'Tools' => [
            'Git',
            'GitHub',
            'Docker',
            'Postman',
            'Linux',
            'Composer',
            'NPM',
        ],
        'Other expertise' => [
            'API Integration',
            'Database Design',
            'Performance Optimization',
            'Technical SEO',
            'Deployment',
            'Server Management',
        ],
    ],
    'skill_descriptions' => [
        'Backend Development' => 'Business logic, REST APIs, and database design for reliable web applications.',
        'Frontend Development' => 'Responsive interfaces built with HTML, CSS, and JavaScript, with a focus on accessibility and usability.',
        'Tools' => 'Tools for version control, development, testing, and deployment.',
        'Other expertise' => 'Connecting services, improving performance, and maintaining applications after launch.',
    ],
    // Add only real client/project/testimonial entries approved for publication.
    'clients' => [],
    // Editable project layouts requested by the owner; not claims of completed client work.
    // Replace the text/image, then set placeholder=false when the real case study is ready.
    'projects' => [
        [
            'slug' => 'project-01',
            'title' => 'Project Name 01',
            'client' => 'Client / organization to be added',
            'category' => 'Business systems',
            'description' => 'Add a short overview of the project, who it serves, and what you built.',
            'problem' => 'Describe the actual business challenge and the client’s requirements.',
            'solution' => 'Explain your contribution and how the application addresses the challenge.',
            'outcome' => 'Add the actual result here. Include measurable outcomes only when supported by evidence.',
            'features' => ['Add the main feature', 'Add another key feature'],
            'tech' => ['Add your tech stack'],
            'image' => null,
            'placeholder' => true,
            'published' => true,
        ],
        [
            'slug' => 'project-02',
            'title' => 'Project Name 02',
            'client' => 'Client / organization to be added',
            'category' => 'Web applications',
            'description' => 'Add a short overview of the project, who it serves, and what you built.',
            'problem' => 'Describe the actual business challenge and the client’s requirements.',
            'solution' => 'Explain your contribution and how the application addresses the challenge.',
            'outcome' => 'Add the actual result here. Include measurable outcomes only when supported by evidence.',
            'features' => ['Add the main feature', 'Add another key feature'],
            'tech' => ['Add your tech stack'],
            'image' => null,
            'placeholder' => true,
            'published' => true,
        ],
        [
            'slug' => 'project-03',
            'title' => 'Project Name 03',
            'client' => 'Client / organization to be added',
            'category' => 'Websites',
            'description' => 'Add a short overview of the project, who it serves, and what you built.',
            'problem' => 'Describe the actual business challenge and the client’s requirements.',
            'solution' => 'Explain your contribution and how the application addresses the challenge.',
            'outcome' => 'Add the actual result here. Include measurable outcomes only when supported by evidence.',
            'features' => ['Add the main feature', 'Add another key feature'],
            'tech' => ['Add your tech stack'],
            'image' => null,
            'placeholder' => true,
            'published' => true,
        ],
        [
            'slug' => 'project-04',
            'title' => 'Project Name 04',
            'client' => 'Client / organization to be added',
            'category' => 'Business systems',
            'description' => 'Add a short overview of the project, who it serves, and what you built.',
            'problem' => 'Describe the actual business challenge and the client’s requirements.',
            'solution' => 'Explain your contribution and how the application addresses the challenge.',
            'outcome' => 'Add the actual result here. Include measurable outcomes only when supported by evidence.',
            'features' => ['Add the main feature', 'Add another key feature'],
            'tech' => ['Add your tech stack'],
            'image' => null,
            'placeholder' => true,
            'published' => true,
        ],
        [
            'slug' => 'project-05',
            'title' => 'Project Name 05',
            'client' => 'Client / organization to be added',
            'category' => 'Web applications',
            'description' => 'Add a short overview of the project, who it serves, and what you built.',
            'problem' => 'Describe the actual business challenge and the client’s requirements.',
            'solution' => 'Explain your contribution and how the application addresses the challenge.',
            'outcome' => 'Add the actual result here. Include measurable outcomes only when supported by evidence.',
            'features' => ['Add the main feature', 'Add another key feature'],
            'tech' => ['Add your tech stack'],
            'image' => null,
            'placeholder' => true,
            'published' => true,
        ],
        [
            'slug' => 'project-06',
            'title' => 'Project Name 06',
            'client' => 'Client / organization to be added',
            'category' => 'Websites',
            'description' => 'Add a short overview of the project, who it serves, and what you built.',
            'problem' => 'Describe the actual business challenge and the client’s requirements.',
            'solution' => 'Explain your contribution and how the application addresses the challenge.',
            'outcome' => 'Add the actual result here. Include measurable outcomes only when supported by evidence.',
            'features' => ['Add the main feature', 'Add another key feature'],
            'tech' => ['Add your tech stack'],
            'image' => null,
            'placeholder' => true,
            'published' => true,
        ],
    ],
    'testimonials' => [],
    'contact_form_enabled' => env('CONTACT_FORM_ENABLED', true),
    'process' => [
        [
            'Discovery',
            'We start with your business, the problem, and what success should look like.',
        ],
        [
            'Planning',
            'A clear scope, sensible architecture, and a timeline we agree on together.',
        ],
        [
            'Development',
            'Your solution takes shape with maintainable code and regular progress updates.',
        ],
        [
            'Testing',
            'We check functionality, usability, security, performance, and responsive layouts.',
        ],
        [
            'Launch',
            'A considered deployment, configuration checks, and a smooth handover.',
        ],
        [
            'Support',
            'Ongoing maintenance, fixes, and improvements as your business evolves.',
        ],
    ],
    'reasons' => [
        '6+ years of development experience',
        'Business-oriented approach',
        'Clean & maintainable code',
        'Responsive communication',
        'Performance-focused development',
        'SEO-friendly development',
        'Scalable architecture',
        'Post-launch support',
    ],
];
